#!/usr/bin/env php
<?PHP
/*************************************************************
*                  _         _       _        _
*    ___ _ __ ___ | |_ _ __ | | __ _| |_ _ __(_)_ __   ___
*   / __| '_ ` _ \| __| '_ \| |/ _` | __| '__| | '_ \ / _ \
*   \__ \ | | | | | |_| |_) | | (_| | |_| |  | | | | |  __/
*   |___/_| |_| |_|\__| .__/|_|\__,_|\__|_|  |_|_| |_|\___|
*                     |_|               _____
*                                 ||    |   D
*   A custom SMTP Honeypot        ||    |   |
*   written in PHP with focus     ||    |   |
*   on gathering intel on threat  ||    \___|             _
*   actors and for doing spam     ||      | |  _______  -( (-
*   forensic work                 ||      |__'(-------)  '-'
*                                 ||          |       /
*  (c) 2024 - THUGSred            ||     ___,-\__..__|__
*
*  Peanut Butter Jelly Time!
*
*  https://github.com/kawaiipantsu/smtplatrine
*/

// Allow the script to hang around waiting for connections
set_time_limit(0);

// Set application name
cli_set_process_title("smtplatrine");

// Let's check we have the requirements to run the application
// We moved this away from the autoloader as then we can use that from www as well where these extensions are not required
if( ! extension_loaded('sockets' ) ) {
	echo "This application requires sockets extension (http://www.php.net/manual/en/sockets.installation.php)\n";
	exit(-1);
}

if( ! extension_loaded('pcntl' ) ) {
	echo "This application requires PCNTL extension (http://www.php.net/manual/en/pcntl.installation.php)\n";
	exit(-1);
}

if( ! extension_loaded('mailparse' ) ) {
	echo "This application requires mailparse extension (https://www.php.net/manual/en/mailparse.installation.php)\n";
	exit(-1);
}

// Try using my makeshift autoloader ...
// This is junk, but it works for now.
require_once 'vendor/autoload.php';

// Get the user info, running this script
$mainUserInfo = posix_getpwuid(posix_geteuid());

// Setup logging for the main application
$logger = new \Controller\Logger(basename(__FILE__,'.php'),__NAMESPACE__);

// As soon as the logger is up, we can say hello in the log!
$logger->logMessage(">>> SMTPLATRINE - A custom SMTP-Honeypot written in PHP :)","NOTICE");

// Setup server handing
$socketServer = new \Socket\Server;

// Setup signal handling
$signalHandler = new \Utils\Signals();

// Make the serverObject available to the signal handler
$signalHandler->setServerObject($socketServer);

// Delcare ticks for signal handling
declare(ticks=1);

// Enable async signals
pcntl_async_signals(true);

// Handle ^C in terminal etc
pcntl_signal(SIGINT, [$signalHandler, 'doSIGINT']);
// Handle kill (Terminated) signal
pcntl_signal(SIGTERM, [$signalHandler, 'doSIGTERM']);
pcntl_signal(SIGQUIT, [$signalHandler, 'doSIGTERM']);
//pcntl_signal(SIGKILL, [$signalHandler, 'doSIGTERM']); // This is not catchable

// Handle hup signal
pcntl_signal(SIGHUP, [$signalHandler, 'doSIGHUP']);
// This is Magic sauce, we ignore the signal from child processes
// This eliminates the need for a signal handler in the parent process
// And we will have no hanging zombie processes!
pcntl_signal(SIGCHLD, [$signalHandler, 'doSIGCHLD']);
//pcntl_signal(SIGCHLD, SIG_IGN);

// Other Signals that we want to catch for logging but not act on
pcntl_signal(SIGUSR1, [$signalHandler, 'doNOTHING']);
pcntl_signal(SIGUSR2, [$signalHandler, 'doNOTHING']);
pcntl_signal(SIGALRM, [$signalHandler, 'doNOTHING']);
pcntl_signal(SIGSEGV, [$signalHandler, 'doNOTHING']);
pcntl_signal(SIGCONT, [$signalHandler, 'doNOTHING']);
//pcntl_signal(SIGSTOP, [$signalHandler, 'doNOTHING']); // This is not catchable

// Enable logging for this script (not underlying classes)
$logger->enableDisplay();
$logger->enableReporting(E_ALL);

// Before we start, let's make some sanity checks that we nee to do as "root"
// Check if we want to run clients in non-privileged mode and if so do we have the right permissions
$_config = parse_ini_file(__DIR__ . '/etc/server.ini',true);
$non_privileged = trim($_config['server']['server_spawn_clients_as_non_privileged']) == "1" ? true : false;
$nonPrivUser = $_config['non_privileged']['non_privileged_user'];
$nonPrivGroup = $_config['non_privileged']['non_privileged_group'];
$attachmentPath = $_config['smtp']['smtp_attachments_path'];
$_config = parse_ini_file(__DIR__ . '/etc/logger.ini',true);
$logPath = $_config['output_file']['output_file_path'];
$logFileMain = $_config['output_file']['output_file_main'];
$logFileError = $_config['output_file']['output_file_error'];
$logFileDebug = $_config['output_file']['output_file_debug'];
unset($_config);

if ($non_privileged) {
    // We require non-privileged user to be set for the connection handler
    // Check if file permissions are set correctly

    // Get UID and GID of the user and group
    $_uid = posix_getpwnam($nonPrivUser);
    $_gid = posix_getgrnam($nonPrivGroup);
    if ( $_uid && $_gid ) {
        $nonPrivGroupGID = $_gid['gid'];
        $nonPrivUserUID = $_uid['uid'];
        $logger->logMessage("[server] Permission check on ".$nonPrivUser."(".$nonPrivUserUID.") and group ".$nonPrivGroup."(".$nonPrivGroupGID.") for non-privileged mode");
    } else {
        $logger->logErrorMessage("[server] Unable to find user ".$nonPrivUser." or group ".$nonPrivGroup." for non-privileged mode");
        exit(1);
    }

    // Log path
    if ( substr($logPath, 0, 1) != '/' ) $logPath = __DIR__ . '/' . $logPath;
    if ( substr($logPath, -1) != '/' ) $logPath .= '/';
    // Attachments path
    if ( substr($attachmentPath, 0, 1) != '/' ) $attachmentPath = __DIR__ . '/' . $attachmentPath;
    if ( substr($attachmentPath, -1) != '/' ) $attachmentPath .= '/';

    // Let's do the magic ...
    $perms = new \Utils\Permissions();
    $_res = $perms->isDirWriteable($logPath, $nonPrivUserUID, $nonPrivGroupGID);
    if ( $_res === false ) {
        $logger->logErrorMessage("[server] Log path ".$logPath." is not writeable by ".$nonPrivUser."(".$nonPrivUserUID.") or group ".$nonPrivGroup."(".$nonPrivGroupGID.")");
        exit(1);
    }
}

// Make sure we have certificate if ready to use
$socketServer->createSSLCert();

// Setup the server
$socketServer->setConnectionHandler('\Socket\ConnectionHandler');

// Activate the server and await incoming connections
$socketServer->start();
$socketServer->listen();

// Send application ENDED log - Just in case we ever get here
// But in most cases we will not get here as we exit out of the loop
// inside different signal handlers before we get here

$logger->logMessage(">>> SMTPLATRINE - Goodbye!","NOTICE");

exit(0);

?>